/***************************************
 * AUTO-GENERATED FILE, DO NOT EDIT!!! *
 * Generated by: tools/config.py       *
 ***************************************/

/* Platform */
#define PLATFORM ia32
#define PLATFORM_ia32

/* CPU type */
#define PROCESSOR pentium4
#define PROCESSOR_pentium4

/* RAM disk format */
#define RDFMT ext4fs
#define RDFMT_ext4fs

/* Kernel architecture */
#define KARCH ia32
#define KARCH_ia32

/* User space architecture */
#define UARCH ia32
#define UARCH_ia32

/* Boot architecture */
#define BARCH ia32
#define BARCH_ia32

/* Compiler */
#define COMPILER gcc_cross
#define COMPILER_gcc_cross

/* Fences */
#define CONFIG_FENCES_P4

/* IOMAP bitmap support */
#define CONFIG_IOMAP_BITMAP

/* ACPI support */
#define CONFIG_ACPI

/* Hierarchical page tables support */
#define CONFIG_PAGE_PT

/* Software integer division support */
#define CONFIG_SOFTINT

/* Multiboot standard support */
#define CONFIG_MULTIBOOT

/* FPU support */
#define CONFIG_FPU

/* Support for SMP */
#define CONFIG_SMP

/* Debug build */
#define CONFIG_DEBUG

/* Deadlock detection support for spinlocks */
#define CONFIG_DEBUG_SPINLOCK

/* Lazy FPU context switching */
#define CONFIG_FPU_LAZY

/* Support for userspace debuggers */
#define CONFIG_UDEBUG

/* Kernel console support */
#define CONFIG_KCONSOLE

/* Kernel symbol information */
#define CONFIG_SYMTAB

/* Compile kernel tests */
#define CONFIG_TEST

/* Kernel RCU algorithm */
#define RCU PREEMPT_A
#define RCU_PREEMPT_A

/* Input device class */
#define CONFIG_HID_IN generic
#define CONFIG_HID_IN_generic

/* Output device class */
#define CONFIG_HID_OUT generic
#define CONFIG_HID_OUT_generic

/* PC keyboard support */
#define CONFIG_PC_KBD

/* Support for i8042 controller */
#define CONFIG_I8042

/* EGA support */
#define CONFIG_EGA

/* Framebuffer support */
#define CONFIG_FB

/* Default framebuffer mode */
#define CONFIG_BFB_MODE 1024x768
#define CONFIG_BFB_MODE_1024x768

/* Default framebuffer depth */
#define CONFIG_BFB_BPP 16
#define CONFIG_BFB_BPP_16

/* Dynamic linking support */
#define CONFIG_RTLD

/* Build shared libraries */
#define CONFIG_BUILD_SHARED_LIBS

/* Link against shared libraries */
#define CONFIG_USE_SHARED_LIBS

/* OHCI root hub port power switching */
#define OHCI_POWER_SWITCH ganged
#define OHCI_POWER_SWITCH_ganged

/* GRUB boot loader architecture */
#define GRUB_ARCH pc
#define GRUB_ARCH_pc

/* Default framebuffer width */
#define CONFIG_BFB_WIDTH 1024
#define CONFIG_BFB_WIDTH_1024

/* Default framebuffer height */
#define CONFIG_BFB_HEIGHT 768
#define CONFIG_BFB_HEIGHT_768

#define REVISION 2585M (jakub@jermar.eu-20170226220046-vm693cb9egojfqkj)
#define TIMESTAMP_UNIX 1490430764
#define TIMESTAMP 2017-03-25 10:32:44
