
/***************************************************************************** 
 * AUTO-GENERATED FILE, DO NOT EDIT!!!
 * Generated by: tools/autogen.py
 * Generated from: genarch/include/genarch/multiboot/multiboot_info_struct.ag
 *****************************************************************************/

#ifndef AUTOGEN_MULTIBOOT_INFO_H
#define AUTOGEN_MULTIBOOT_INFO_H

#ifndef __ASM__
#include <typedefs.h>
#endif

#define MULTIBOOT_INFO_OFFSET_FLAGS 0
#define MULTIBOOT_INFO_SIZE_FLAGS 4
#define MULTIBOOT_INFO_OFFSET_MEM_LOWER 4
#define MULTIBOOT_INFO_SIZE_MEM_LOWER 4
#define MULTIBOOT_INFO_OFFSET_MEM_UPPER 8
#define MULTIBOOT_INFO_SIZE_MEM_UPPER 4
#define MULTIBOOT_INFO_OFFSET_BOOT_DEVICE 12
#define MULTIBOOT_INFO_SIZE_BOOT_DEVICE 4
#define MULTIBOOT_INFO_OFFSET_CMD_LINE 16
#define MULTIBOOT_INFO_SIZE_CMD_LINE 4
#define MULTIBOOT_INFO_OFFSET_MODS_COUNT 20
#define MULTIBOOT_INFO_SIZE_MODS_COUNT 4
#define MULTIBOOT_INFO_OFFSET_MODS_ADDR 24
#define MULTIBOOT_INFO_SIZE_MODS_ADDR 4
#define MULTIBOOT_INFO_OFFSET_SYMS 28
#define MULTIBOOT_INFO_SIZE_SYMS 16
#define MULTIBOOT_INFO_SYMS_ITEM_SIZE 4
#define MULTIBOOT_INFO_OFFSET_MMAP_LENGTH 44
#define MULTIBOOT_INFO_SIZE_MMAP_LENGTH 4
#define MULTIBOOT_INFO_OFFSET_MMAP_ADDR 48
#define MULTIBOOT_INFO_SIZE_MMAP_ADDR 4
#define MULTIBOOT_INFO_SIZE 52

#ifndef __ASM__
typedef struct multiboot_info {
	uint32_t flags;
	uint32_t mem_lower;
	uint32_t mem_upper;
	uint32_t boot_device;
	uint32_t cmd_line;
	uint32_t mods_count;
	uint32_t mods_addr;
	uint32_t syms[4];
	uint32_t mmap_length;
	uint32_t mmap_addr;
} __attribute__ ((packed)) multiboot_info_t;
#endif

#endif
	
