
/***************************************************************************** 
 * AUTO-GENERATED FILE, DO NOT EDIT!!!
 * Generated by: tools/autogen.py
 * Generated from: genarch/include/genarch/multiboot/multiboot_memmap_struct.ag
 *****************************************************************************/

#ifndef AUTOGEN_MULTIBOOT_MEMMAP_H
#define AUTOGEN_MULTIBOOT_MEMMAP_H

#ifndef __ASM__
#include <typedefs.h>
#include <arch/boot/memmap_struct.h>
#endif

#define MULTIBOOT_MEMMAP_OFFSET_SIZE 0
#define MULTIBOOT_MEMMAP_SIZE_SIZE 4
#define MULTIBOOT_MEMMAP_OFFSET_MM_INFO 4
#define MULTIBOOT_MEMMAP_SIZE_MM_INFO 20
#define MULTIBOOT_MEMMAP_SIZE 24

#ifndef __ASM__
typedef struct multiboot_memmap {
	uint32_t size;
	e820memmap_t mm_info;
} __attribute__ ((packed)) multiboot_memmap_t;
#endif

#endif
	
